// Generated by tools/kfparticle/import_core.py; see PROVENANCE.md.
namespace star_analyzer_kfp { // local ABI isolation
// -*- C++ Header -*-
/*
==================================================
Authors: A.Mithran, P. Kisel, I. Kisel
Emails: mithran@fias.uni-frankfurt.de
==================================================
*/

#ifndef STAR_ANALYZER_VENDOR_SIMD_MACROS_H
#define STAR_ANALYZER_VENDOR_SIMD_MACROS_H

} // namespace star_analyzer_kfp
#include "simd_detect.h"
namespace star_analyzer_kfp { // local ABI isolation

#define KFP_SIMD_INLINE inline __attribute__((always_inline))

#endif // !STAR_ANALYZER_VENDOR_SIMD_MACROS_H
} // namespace star_analyzer_kfp
