/********************************************************************
* /gpfs/mnt/gpfs01/star/pwg/oura/star-analyzer/common/macro/checkHistAnaPhi_C_ACLiC_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /gpfs/mnt/gpfs01/star/pwg/oura/star-analyzer/common/macro/checkHistAnaPhi_C_ACLiC_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablecheckHistAnaPhi_C_ACLiC_dict();
extern void G__cpp_setup_inheritancecheckHistAnaPhi_C_ACLiC_dict();
extern void G__cpp_setup_typetablecheckHistAnaPhi_C_ACLiC_dict();
extern void G__cpp_setup_memvarcheckHistAnaPhi_C_ACLiC_dict();
extern void G__cpp_setup_globalcheckHistAnaPhi_C_ACLiC_dict();
extern void G__cpp_setup_memfunccheckHistAnaPhi_C_ACLiC_dict();
extern void G__cpp_setup_funccheckHistAnaPhi_C_ACLiC_dict();
extern void G__set_cpp_environmentcheckHistAnaPhi_C_ACLiC_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/gpfs/mnt/gpfs01/star/pwg/oura/star-analyzer/common/macro/checkHistAnaPhi.C"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__checkHistAnaPhi_C_ACLiC_dictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__checkHistAnaPhi_C_ACLiC_dictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__checkHistAnaPhi_C_ACLiC_dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__checkHistAnaPhi_C_ACLiC_dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__checkHistAnaPhi_C_ACLiC_dictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__checkHistAnaPhi_C_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__checkHistAnaPhi_C_ACLiC_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__checkHistAnaPhi_C_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__checkHistAnaPhi_C_ACLiC_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__checkHistAnaPhi_C_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__checkHistAnaPhi_C_ACLiC_dictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__checkHistAnaPhi_C_ACLiC_dictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__checkHistAnaPhi_C_ACLiC_dictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__checkHistAnaPhi_C_ACLiC_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__checkHistAnaPhi_C_ACLiC_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__checkHistAnaPhi_C_ACLiC_dictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__checkHistAnaPhi_C_ACLiC_dictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__checkHistAnaPhi_C_ACLiC_dictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR;

/* STUB derived class for protected member access */
