// Generated by tools/kfparticle/import_core.py; see PROVENANCE.md.
namespace star_analyzer_kfp { // local ABI isolation
// -*- C++ Header -*-
/*
==================================================
Authors: A.Mithran;
Emails: mithran@fias.uni-frankfurt.de
==================================================
*/

#ifndef STAR_ANALYZER_VENDOR_SIMD_SSE_CONSTANTS_H
#define STAR_ANALYZER_VENDOR_SIMD_SSE_CONSTANTS_H

} // namespace star_analyzer_kfp
#include <cstddef>
namespace star_analyzer_kfp { // local ABI isolation

namespace KFP {
namespace SIMD {

constexpr int SimdSize{16};
constexpr int SimdLen{4};

} // namespace SIMD
} // namespace KFP

#endif // !STAR_ANALYZER_VENDOR_SIMD_SSE_CONSTANTS_H
} // namespace star_analyzer_kfp
