// Generated by tools/kfparticle/import_core.py; see PROVENANCE.md.
namespace star_analyzer_kfp { // local ABI isolation
// -*- C++ Header -*-
/*
==================================================
Authors: A.Mithran;
Emails: mithran@fias.uni-frankfurt.de
==================================================
*/

#ifndef STAR_ANALYZER_VENDOR_KFP_SIMD_H
#define STAR_ANALYZER_VENDOR_KFP_SIMD_H

// Determine instruction set, and define platform-dependent functions
} // namespace star_analyzer_kfp
#include "Utils/macros.h"
namespace star_analyzer_kfp { // local ABI isolation
// #include "Utils/memory.h"

// Select appropriate header files depending on instruction set
#if defined(KFP_SIMD_AVX)
#error "[Error] (simd.h): KFParticle SIMD AVX not implemented."
// #include "AVX/types.h"
#elif defined(KFP_SIMD_SSE)
} // namespace star_analyzer_kfp
#include "SSE/types.h"
namespace star_analyzer_kfp { // local ABI isolation
#else
#error "[Error] (simd.h): KFParticle SIMD Scalar not implemented."
// #include "Scalar/types.h"
} // namespace star_analyzer_kfp
#include "Scalar/types.h"
namespace star_analyzer_kfp { // local ABI isolation
#endif

#endif // !STAR_ANALYZER_VENDOR_KFP_SIMD_H
} // namespace star_analyzer_kfp
