#!/usr/bin/env python3
"""Farm jobs that count the events actually present in a set of PicoDst.

The Step 7 ledger compares three numbers per input file: what the catalog said (the second column
of every SUMS .list), what the production's hCounters recorded, and what the file really holds.
The first two disagree by 3.6 % over the whole data set, and only the third settles whether that
is a catalog definition or lost events.

Counting is cheap -- TTree::GetEntries reads the header, not the data -- but reaching the file is
not: the login node copies from xrootd at ~170 kB/s, and the container's ROOT has no Netx plugin,
so a remote open fails outright. A farm node has neither problem. Each job therefore stages its
files with xrdcp and counts the local copy, deleting it immediately afterwards.

Usage
  script/submit_pico_event_count.py --list urls.txt --workdir <dir> --repo <repo> [--shards N]

  urls.txt: "<url-or-path> <catalogEvents>" per line, exactly as the SUMS .list files are written.

The jobs are plain condor submissions, not SUMS: there is no catalog query and no input sandbox,
only a list of URLs. Every path is required and checked before anything is submitted.
"""

import argparse
import os
import subprocess
import sys

IMAGE = "/cvmfs/singularity.opensciencegrid.org/star-bnl/star-sw:latest"
BINDS = ["-B /gpfs:/gpfs", "-B /cvmfs:/cvmfs", "-B /star/u:/star/u",
         "-B /star/nfs4/AFS:/star/nfs4/AFS", "-B /home/starlib:/home/starlib"]

CONDOR_STANZA = """Universe         = vanilla
Notification     = never
Executable       = /bin/sh
Arguments        = "-c 'exec {script}'"
Output           = {log}/{tag}.out
Error            = {log}/{tag}.err
Log              = {log}/condor.log
Initialdir       = {workdir}
GetEnv           = False
request_memory   = {memory}
PeriodicRemove   = (JobStatus == 2) && ((CurrentTime - EnteredCurrentStatus) > {wall})
Queue

"""


def shell_quote(s):
    return "'" + s.replace("'", "'\\''") + "'"


def in_container(command):
    return "singularity exec %s %s /bin/bash -lc %s" % (" ".join(BINDS), IMAGE,
                                                        shell_quote(command))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--list", required=True, help="'<url> <catalogEvents>' per line")
    ap.add_argument("--workdir", required=True, help="where job scripts, logs and results go")
    ap.add_argument("--repo", required=True, help="repository root (holds tools/treecheck)")
    ap.add_argument("--shards", type=int, default=20)
    ap.add_argument("--memory", default="2GB")
    ap.add_argument("--wall", type=int, default=14400)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    if not os.path.isfile(args.list):
        sys.exit("ERROR: list file does not exist: %s" % args.list)
    lines = [l.strip() for l in open(args.list) if l.strip()]
    if not lines:
        sys.exit("ERROR: list file is empty: %s" % args.list)
    repo = os.path.abspath(args.repo)
    macro_path = os.path.join(repo, "tools", "treecheck", "PicoEventCount.C")
    if not os.path.isfile(macro_path):
        sys.exit("ERROR: macro not found: %s" % macro_path)
    workdir = os.path.abspath(args.workdir)
    logdir = os.path.join(workdir, "log")
    jobdir = os.path.join(workdir, "job")
    for d in (workdir, logdir, jobdir):
        if not os.path.isdir(d):
            os.makedirs(d)

    shards = max(1, args.shards)
    per = (len(lines) + shards - 1) // shards
    print("%d files -> %d shards of at most %d" % (len(lines), shards, per))

    condor = []
    for i in range(shards):
        chunk = lines[i * per:(i + 1) * per]
        if not chunk:
            continue
        tag = "picocount_%03d" % i
        shard_list = os.path.join(jobdir, tag + ".list")
        with open(shard_list, "w") as fh:
            fh.write("\n".join(chunk) + "\n")
        result = os.path.join(workdir, "count_%03d.tsv" % i)
        build = "/tmp/%s/picocount_%s" % (os.environ.get("USER", "star"), tag)
        prelude = os.path.join(jobdir, tag + "_prelude.C")
        with open(prelude, "w") as fh:
            fh.write("// Generated by script/submit_pico_event_count.py: keep ACLiC's build\n"
                     "// products on the node's own disk, not on shared GPFS.\n"
                     "void %s_prelude() { gSystem->SetBuildDir(\"%s\", kTRUE); }\n"
                     % (tag, build))

        # The staged-file list is written by the job but named here: the inner shell sees the
        # macro arguments inside single quotes, so a variable would reach ROOT unexpanded.
        local_list = os.path.join(jobdir, tag + ".local.list")
        macro = ("root -b -q %s '%s/tools/treecheck/PicoEventCount.C+(\"%s\",\"%s\")'"
                 % (prelude, repo, local_list, result))
        # Staging is the job's own work, and it is deliberately not silent: a file that cannot be
        # staged is the thing this whole audit is about, so the job records it as a
        # stage_failed row rather than dropping it.
        body = """#!/bin/bash
set -u
echo "host $(hostname)  start $(date)"
SCRATCH=${_CONDOR_SCRATCH_DIR:-/tmp/$USER/%s}
mkdir -p "$SCRATCH/stage" %s || exit 1
LOCAL_LIST=%s
: > "$LOCAL_LIST"
FAILED=$SCRATCH/stage_failed.list
: > "$FAILED"
while read -r url nev; do
  [ -z "$url" ] && continue
  base=$(basename "$url")
  dest=$SCRATCH/stage/$base
  if [ -f "$url" ]; then
    echo "$url $nev" >> "$LOCAL_LIST"
    continue
  fi
  if xrdcp --retry 3 --silent "$url" "$dest"; then
    echo "$dest $nev" >> "$LOCAL_LIST"
  else
    echo "$base $nev stage_failed" >> "$FAILED"
  fi
done < %s
echo "staged $(wc -l < "$LOCAL_LIST")  failed $(wc -l < "$FAILED")"
%s
rc=$?
cat "$FAILED" >> %s.stagefail
rm -rf "$SCRATCH/stage" %s
echo "exit $rc  end $(date)"
exit $rc
""" % (tag, build, local_list, shard_list,
       in_container("export LD_LIBRARY_PATH=${ROOTSYS}/lib:$LD_LIBRARY_PATH; "
                    "cd %s; " % repo + macro),
       result, build)
        script = os.path.join(jobdir, tag + ".sh")
        with open(script, "w") as fh:
            fh.write(body)
        os.chmod(script, 0o755)
        condor.append(CONDOR_STANZA.format(script=script, log=logdir, tag=tag, workdir=workdir,
                                           memory=args.memory, wall=args.wall))

    condor_path = os.path.join(jobdir, "picocount.condor")
    open(condor_path, "w").write("".join(condor))
    if args.dry_run:
        print("dry run: not submitting %s" % condor_path)
        return 0
    print("condor_submit %s" % condor_path)
    return subprocess.call(["condor_submit", condor_path])


if __name__ == "__main__":
    sys.exit(main())
